// Code generated by protoc-gen-go. DO NOT EDIT.
// source: videoService.proto

package videoService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Rectangle struct {
	X                    int32    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rectangle) Reset()         { *m = Rectangle{} }
func (m *Rectangle) String() string { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()    {}
func (*Rectangle) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{0}
}

func (m *Rectangle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rectangle.Unmarshal(m, b)
}
func (m *Rectangle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rectangle.Marshal(b, m, deterministic)
}
func (m *Rectangle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rectangle.Merge(m, src)
}
func (m *Rectangle) XXX_Size() int {
	return xxx_messageInfo_Rectangle.Size(m)
}
func (m *Rectangle) XXX_DiscardUnknown() {
	xxx_messageInfo_Rectangle.DiscardUnknown(m)
}

var xxx_messageInfo_Rectangle proto.InternalMessageInfo

func (m *Rectangle) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Rectangle) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type VideoMetaData struct {
	Size                 *Rectangle `protobuf:"bytes,1,opt,name=Size,proto3" json:"Size,omitempty"`
	MacroBlocks          *Rectangle `protobuf:"bytes,2,opt,name=MacroBlocks,proto3" json:"MacroBlocks,omitempty"`
	BitRate              int32      `protobuf:"varint,3,opt,name=BitRate,proto3" json:"BitRate,omitempty"`
	FrameRate            int32      `protobuf:"varint,4,opt,name=FrameRate,proto3" json:"FrameRate,omitempty"`
	KeyFrameRate         int32      `protobuf:"varint,5,opt,name=KeyFrameRate,proto3" json:"KeyFrameRate,omitempty"`
	AnalogGain           float32    `protobuf:"fixed32,6,opt,name=AnalogGain,proto3" json:"AnalogGain,omitempty"`
	DigitalGain          float32    `protobuf:"fixed32,7,opt,name=DigitalGain,proto3" json:"DigitalGain,omitempty"`
	RefreshType          string     `protobuf:"bytes,8,opt,name=RefreshType,proto3" json:"RefreshType,omitempty"`
	H264Level            string     `protobuf:"bytes,9,opt,name=H264Level,proto3" json:"H264Level,omitempty"`
	H264Profile          string     `protobuf:"bytes,10,opt,name=H264Profile,proto3" json:"H264Profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VideoMetaData) Reset()         { *m = VideoMetaData{} }
func (m *VideoMetaData) String() string { return proto.CompactTextString(m) }
func (*VideoMetaData) ProtoMessage()    {}
func (*VideoMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{1}
}

func (m *VideoMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoMetaData.Unmarshal(m, b)
}
func (m *VideoMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoMetaData.Marshal(b, m, deterministic)
}
func (m *VideoMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoMetaData.Merge(m, src)
}
func (m *VideoMetaData) XXX_Size() int {
	return xxx_messageInfo_VideoMetaData.Size(m)
}
func (m *VideoMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_VideoMetaData proto.InternalMessageInfo

func (m *VideoMetaData) GetSize() *Rectangle {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *VideoMetaData) GetMacroBlocks() *Rectangle {
	if m != nil {
		return m.MacroBlocks
	}
	return nil
}

func (m *VideoMetaData) GetBitRate() int32 {
	if m != nil {
		return m.BitRate
	}
	return 0
}

func (m *VideoMetaData) GetFrameRate() int32 {
	if m != nil {
		return m.FrameRate
	}
	return 0
}

func (m *VideoMetaData) GetKeyFrameRate() int32 {
	if m != nil {
		return m.KeyFrameRate
	}
	return 0
}

func (m *VideoMetaData) GetAnalogGain() float32 {
	if m != nil {
		return m.AnalogGain
	}
	return 0
}

func (m *VideoMetaData) GetDigitalGain() float32 {
	if m != nil {
		return m.DigitalGain
	}
	return 0
}

func (m *VideoMetaData) GetRefreshType() string {
	if m != nil {
		return m.RefreshType
	}
	return ""
}

func (m *VideoMetaData) GetH264Level() string {
	if m != nil {
		return m.H264Level
	}
	return ""
}

func (m *VideoMetaData) GetH264Profile() string {
	if m != nil {
		return m.H264Profile
	}
	return ""
}

type Frame struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{2}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Rectangle)(nil), "Rectangle")
	proto.RegisterType((*VideoMetaData)(nil), "VideoMetaData")
	proto.RegisterType((*Frame)(nil), "Frame")
}

func init() { proto.RegisterFile("videoService.proto", fileDescriptor_c4ee3c3e3f13865b) }

var fileDescriptor_c4ee3c3e3f13865b = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0xce, 0xd2, 0x40,
	0x14, 0x85, 0x33, 0x48, 0x81, 0x5e, 0xd0, 0xc5, 0x2c, 0xcc, 0x04, 0x0c, 0x69, 0xba, 0x91, 0x05,
	0x16, 0x53, 0x8d, 0x7b, 0x09, 0x88, 0x51, 0x49, 0xc8, 0x60, 0x0c, 0x2c, 0x87, 0x7a, 0xa9, 0x13,
	0x4b, 0x87, 0x94, 0x11, 0x83, 0x2f, 0xe8, 0x53, 0xfc, 0xef, 0xf2, 0x67, 0x6e, 0x03, 0x94, 0xc5,
	0x9f, 0xb0, 0xeb, 0xf9, 0xce, 0xb9, 0xb7, 0x93, 0x7b, 0x80, 0x1f, 0xf5, 0x4f, 0x34, 0x4b, 0x2c,
	0x8e, 0x3a, 0xc1, 0x68, 0x5f, 0x18, 0x6b, 0xba, 0xbd, 0xd4, 0x98, 0x34, 0xc3, 0x11, 0xa9, 0xcd,
	0x9f, 0xed, 0x08, 0x77, 0x7b, 0x7b, 0x2a, 0xcd, 0xf0, 0x35, 0xf8, 0x12, 0x13, 0xab, 0xf2, 0x34,
	0x43, 0xde, 0x01, 0xb6, 0x12, 0x2c, 0x60, 0x03, 0x4f, 0xb2, 0x95, 0x53, 0x6b, 0x51, 0x2b, 0xd5,
	0x3a, 0x7c, 0xa8, 0xc1, 0xf3, 0x1f, 0x6e, 0xf9, 0x1c, 0xad, 0x9a, 0x28, 0xab, 0x78, 0x1f, 0xea,
	0x4b, 0xfd, 0x0f, 0x69, 0xa0, 0x1d, 0x43, 0x74, 0xd9, 0x23, 0x89, 0xf3, 0x21, 0xb4, 0xe7, 0x2a,
	0x29, 0xcc, 0x38, 0x33, 0xc9, 0xef, 0x03, 0x6d, 0xba, 0x8d, 0x55, 0x6d, 0x2e, 0xa0, 0x39, 0xd6,
	0x56, 0x2a, 0x8b, 0xe2, 0x19, 0xfd, 0xf3, 0x2c, 0xf9, 0x2b, 0xf0, 0x3f, 0x15, 0x6a, 0x87, 0xe4,
	0xd5, 0xc9, 0xbb, 0x02, 0x1e, 0x42, 0xe7, 0x2b, 0x9e, 0xae, 0x01, 0x8f, 0x02, 0x37, 0x8c, 0xf7,
	0x01, 0x3e, 0xe6, 0x2a, 0x33, 0xe9, 0x4c, 0xe9, 0x5c, 0x34, 0x02, 0x36, 0xa8, 0xc9, 0x0a, 0xe1,
	0x01, 0xb4, 0x27, 0x3a, 0xd5, 0x56, 0x65, 0x14, 0x68, 0x52, 0xa0, 0x8a, 0x5c, 0x42, 0xe2, 0xb6,
	0xc0, 0xc3, 0xaf, 0xef, 0xa7, 0x3d, 0x8a, 0x56, 0xc0, 0x06, 0xbe, 0xac, 0x22, 0xf7, 0xca, 0xcf,
	0xf1, 0x87, 0xf7, 0xdf, 0xf0, 0x88, 0x99, 0xf0, 0xc9, 0xbf, 0x02, 0x37, 0xef, 0xc4, 0xa2, 0x30,
	0x5b, 0x9d, 0xa1, 0x80, 0x72, 0xbe, 0x82, 0xc2, 0x1e, 0x78, 0xf4, 0x60, 0xce, 0xa1, 0xee, 0xce,
	0x4b, 0x67, 0xed, 0x48, 0xfa, 0x8e, 0xff, 0x33, 0xf0, 0xe8, 0xf8, 0x3c, 0x86, 0xd6, 0xa5, 0x80,
	0x97, 0x51, 0xd9, 0x6c, 0x74, 0x6e, 0x36, 0x9a, 0xba, 0x66, 0xbb, 0x2f, 0xa2, 0xdb, 0xa2, 0x86,
	0xd0, 0x22, 0x20, 0xd5, 0xdf, 0x27, 0x67, 0x1a, 0x11, 0xfd, 0xfd, 0x2d, 0xe3, 0x6f, 0xc0, 0xa7,
	0xf4, 0x97, 0xc5, 0x74, 0x76, 0x5f, 0x7c, 0x6e, 0xac, 0x36, 0xf9, 0x5d, 0xdb, 0x37, 0x0d, 0x72,
	0xde, 0x3d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x43, 0xac, 0xdc, 0xe6, 0xa9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VideoClient is the client API for Video service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VideoClient interface {
	MetaData(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VideoMetaData, error)
	VideoRaw(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Video_VideoRawClient, error)
	VideoJPEG(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Video_VideoJPEGClient, error)
	MotionRaw(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Video_MotionRawClient, error)
}

type videoClient struct {
	cc *grpc.ClientConn
}

func NewVideoClient(cc *grpc.ClientConn) VideoClient {
	return &videoClient{cc}
}

func (c *videoClient) MetaData(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VideoMetaData, error) {
	out := new(VideoMetaData)
	err := c.cc.Invoke(ctx, "/Video/MetaData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) VideoRaw(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Video_VideoRawClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Video_serviceDesc.Streams[0], "/Video/VideoRaw", opts...)
	if err != nil {
		return nil, err
	}
	x := &videoVideoRawClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Video_VideoRawClient interface {
	Recv() (*Frame, error)
	grpc.ClientStream
}

type videoVideoRawClient struct {
	grpc.ClientStream
}

func (x *videoVideoRawClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *videoClient) VideoJPEG(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Video_VideoJPEGClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Video_serviceDesc.Streams[1], "/Video/VideoJPEG", opts...)
	if err != nil {
		return nil, err
	}
	x := &videoVideoJPEGClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Video_VideoJPEGClient interface {
	Recv() (*Frame, error)
	grpc.ClientStream
}

type videoVideoJPEGClient struct {
	grpc.ClientStream
}

func (x *videoVideoJPEGClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *videoClient) MotionRaw(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Video_MotionRawClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Video_serviceDesc.Streams[2], "/Video/MotionRaw", opts...)
	if err != nil {
		return nil, err
	}
	x := &videoMotionRawClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Video_MotionRawClient interface {
	Recv() (*Frame, error)
	grpc.ClientStream
}

type videoMotionRawClient struct {
	grpc.ClientStream
}

func (x *videoMotionRawClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VideoServer is the server API for Video service.
type VideoServer interface {
	MetaData(context.Context, *empty.Empty) (*VideoMetaData, error)
	VideoRaw(*empty.Empty, Video_VideoRawServer) error
	VideoJPEG(*empty.Empty, Video_VideoJPEGServer) error
	MotionRaw(*empty.Empty, Video_MotionRawServer) error
}

// UnimplementedVideoServer can be embedded to have forward compatible implementations.
type UnimplementedVideoServer struct {
}

func (*UnimplementedVideoServer) MetaData(ctx context.Context, req *empty.Empty) (*VideoMetaData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetaData not implemented")
}
func (*UnimplementedVideoServer) VideoRaw(req *empty.Empty, srv Video_VideoRawServer) error {
	return status.Errorf(codes.Unimplemented, "method VideoRaw not implemented")
}
func (*UnimplementedVideoServer) VideoJPEG(req *empty.Empty, srv Video_VideoJPEGServer) error {
	return status.Errorf(codes.Unimplemented, "method VideoJPEG not implemented")
}
func (*UnimplementedVideoServer) MotionRaw(req *empty.Empty, srv Video_MotionRawServer) error {
	return status.Errorf(codes.Unimplemented, "method MotionRaw not implemented")
}

func RegisterVideoServer(s *grpc.Server, srv VideoServer) {
	s.RegisterService(&_Video_serviceDesc, srv)
}

func _Video_MetaData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).MetaData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Video/MetaData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).MetaData(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_VideoRaw_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VideoServer).VideoRaw(m, &videoVideoRawServer{stream})
}

type Video_VideoRawServer interface {
	Send(*Frame) error
	grpc.ServerStream
}

type videoVideoRawServer struct {
	grpc.ServerStream
}

func (x *videoVideoRawServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

func _Video_VideoJPEG_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VideoServer).VideoJPEG(m, &videoVideoJPEGServer{stream})
}

type Video_VideoJPEGServer interface {
	Send(*Frame) error
	grpc.ServerStream
}

type videoVideoJPEGServer struct {
	grpc.ServerStream
}

func (x *videoVideoJPEGServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

func _Video_MotionRaw_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VideoServer).MotionRaw(m, &videoMotionRawServer{stream})
}

type Video_MotionRawServer interface {
	Send(*Frame) error
	grpc.ServerStream
}

type videoMotionRawServer struct {
	grpc.ServerStream
}

func (x *videoMotionRawServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

var _Video_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Video",
	HandlerType: (*VideoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MetaData",
			Handler:    _Video_MetaData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VideoRaw",
			Handler:       _Video_VideoRaw_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "VideoJPEG",
			Handler:       _Video_VideoJPEG_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MotionRaw",
			Handler:       _Video_MotionRaw_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "videoService.proto",
}
